### ISSUE TITLE
FYI: Prisma is now continuously testing this driver adapter

### ISSUE THREAD

**Issue by janpio** [lucasthevenet/pglite-utils#10]
I just created a minimal ecosystem test that uses this driver adapter: https://github.com/prisma/ecosystem-tests/tree/dev/driver-adapters/pglite-node-basic

This will automatically be updated to Prisma's internal `dev` versions, so if we break this driver adapter somehow, we will notice and then can reach out to you. This will also be updated for releases in this repository/package, and if it introduces an obvious regression, we will also notice and let you know. (Note that the tests run there are pretty limited, so they are not a replacement for actual tests of the driver adapter.)

Wheeee! :D

**Comment by lucasthevenet** [comment]
Perfect! Thank you so much for the involvement
